FireboltMediaPlayer/FireboltMediaPlayer.cpp, FireboltMediaPlayer/FireboltMediaPlayer.h
The in-process portion of the FireboltMediaPlayer cannot handle the
out-of-process portion stopped unexpectedly; either killed or crashing.
This is because it is assuming the error codes that are returned rather
than handing unexpected ones, such as ERROR_CONNECTION_CLOSED.
Reason for change: explicitly killing the FireboltMediaPlayer
out-of-process micro-service or having it crashes cause wpeframwork
to crash.
Risks: Low
Test Procedure: Launch FireboltMediaPlayer and use kill -9 on its
process.
Signed-off-by: Mikolaj Staworzynski <mikolaj.staworzynski@redembedded.com>
Original source of patch:
https://github.com/rdkcentral/rdkservices/pull/1336/commits/7e4bf2627dceb522818f63478b04e4dccfba8338
Removed one block of patch that we already have:
- Unregister(_T("setPosition"));
+ …
=> DELIA-50319: wpeframework service crash

DisplaySettings/DisplaySettings.cpp, helpers/tptimer.h
devicesettings-hal-headers changed; some enums have been converted to structs -  upstream commit c06251c2ad5f2cc6fe9148e1026d1db4c953b1d4 had to be partially backported to fix that.
Also, tptimer.cpp was breaking because of unnecessary plugins/plugins.h include (probably started happening after Thunder update)
=> ONEMPERS-135 fix DisplaySetting plugin after rdk devicesettings updates

OpenCDMi/OCDM.config
Signed-off-by: Gurdal Oruklu <gurdal_oruklu@comcast.com>
=> COMCAST: set OCDM sharepath to /tmp/OCDM

FireboltMediaPlayer/CMakeLists.txt
source of patch: part of the:
commit 280dc6ded13f360afaf516ba6762570b3b97a025
Author: Lukasz Wasylyk <lukasz.wasylyk@redembedded.com>
=> ONEM-21597: Firebolt Media Player compilation error fix.

CMakeLists.txt, HdmiCec/HdmiCec.cpp, LgiHdmiCec/CMakeLists.txt, LgiHdmiCec/LgiHdmiCec.config, LgiHdmiCec/LgiHdmiCec.cpp, LgiHdmiCec/LgiHdmiCec.h, LgiHdmiCec/LgiHdmiCec.json, LgiHdmiCec/LgiHdmiCecPlugin.json, LgiHdmiCec/Module.cpp, LgiHdmiCec/Module.h, LgiHdmiCec/README.md, LgiHdmiCec/doc/LgiHdmiCecPlugin.md
This changeset copies the original org.rdk.HdmiCec plugin to a separate directory and adds the following methods:
enableOneTouchView,
triggerAction,
setCecPingInterval,
getConnectedDevices,
setName,
setOneTouchViewPolicy.
Additionally, the following event is added:
onDevicesChanged.
It has been observed that deactivating the plugin without disabling it first (calling the setEnabled method with "false") caused WPE Framework to crash. As a solution, the plugin Deinitialize() functions for both the original and new plugins now try to disable the respective plugin.
=> Add com.lgi.rdk.HdmiCec WPE Framework plugin 

CMakeLists.txt, LgiHdcpProfile/CMakeLists.txt, LgiHdcpProfile/LgiHdcpProfile.config, LgiHdcpProfile/LgiHdcpProfile.cpp, LgiHdcpProfile/LgiHdcpProfile.h, LgiHdcpProfile/LgiHdcpProfile.json, LgiHdcpProfile/LgiHdcpProfilePlugin.json, LgiHdcpProfile/Module.cpp, LgiHdcpProfile/Module.h, LgiHdcpProfile/README.md
And adding new plugin, LgiHdcpProfile - that extends org.rdk.HdcpProfile
and contains also Lgi addon methods; the callsign is com.lgi.rdk.HdcpProfile
=> ONEMPERS-139 integrating LgiHdcpProfile Thunder plugin

OpenCDMi/CMakeLists.txt, OpenCDMi/FrameworkRPC.cpp, OpenCDMi/OCDM.cpp, OpenCDMi/OCDM.h, OpenCDMi/OCDMJsonRpc.cpp
[ONEM-22983] drm initialization events for COMRPC and JSONRPC
[ONEM-22984] Event generation and re-trying implementation
The whole is builded correctly here: https://gerrit.onemw.net/c/meta-lgi-om-common/+/87824 (includes API changes)
Example verification build: https://jenkins.onemw.net/job/EngineeringBuild/7898/
possible to receive after registration to:
{"jsonrpc": "2.0","id": 2, "method": "OCDM.1.register","params": { "event": "drmalreadyinitialized", "id" : "OCDM" }}
event:
{"jsonrpc":"2.0","method":"OCDM.drmalreadyinitialized","params":{"drm":"PlayReady"}}
and after registration to:
{"jsonrpc": "2.0","id": 2, "method": "OCDM.1.register","params": { "event": "drminitializationstatus", "id" : "OCDM" }}
events:
PlayReady BUSY (used by another process)" …
=> [ONEM-22983] drm initialization events for COMRPC and JSONRPC

helpers/utils.h
this fixes compilation warnings like:
In file included from (...)/rdkservices/helpers/utils.cpp:27:0:
(...)/helpers/utils.cpp: In destructor 'Utils::ThreadRAII::~ThreadRAII()'
(...)/helpers/utils.h:48:241: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
That come from LOGERR macros, defined here
=> fix compilation warnings when using LOGGER macros

OpenCDMi/CMakeLists.txt, OpenCDMi/FrameworkRPC.cpp, helpers/ReportErrors.h
Part provided here is for OCDM errors in initialization retrying flow (while creating a new session)
All compiled and validated together here: https://gerrit.onemw.net/c/meta-lgi-om-common/+/87319
Example validation build: https://jenkins.onemw.net/job/EngineeringBuild/8146/
=> [ONEM-15903] ODH reporting for OCDM - initialization retry

XCast/CMakeLists.txt, XCast/RtNotifier.h, XCast/RtXcastConnector.cpp, XCast/RtXcastConnector.h, XCast/XCast.cpp, XCast/XCast.h, XCast/XCastSystemRemoteObject.cpp, XCast/XCastSystemRemoteObject.h
XCast support for system application request
introduced in DIAL 2.2 specs - 'sleep' method
this is only adding all the wiring necessary,
XCast::onXcastSystemApplicationSleepRequest is
still to be implemented.
=> ONEMPERS-206 XCast: /app/system support

TraceControl/Module.h
From: Adam Stolcenburg <astolcenburg.contractor@libertyglobal.com>
Date: Tue, 9 Nov 2021 12:11:43 +0100
Header file interfaces/definitions.h includes the following headers
that are not always available:
- interfaces/IComposition.h
- interfaces/IStream.h
- interfaces/IVoiceHandler.h
- interfaces/IPower.h
=> ONEM-23137: Remove redundant inclusion of interfaces/definitions.h

OpenCDMi/OCDM.config
default /tmp/ocdm changed to /tmp/OCDM/ocdm
=> [ONEM-24034] OCDM connector reconfigured

XCast/XCast.cpp
The commit changes XCast plugin reconnection behavior. The previous
implementation retries connection to the remote server up to 4 times, with
the increasing interval before retries. There is no reason to stop retrying as
plugin without this connection is useless, so right now it repeats the
fourth retry (60 seconds timeout) till success.
=> ONEMPERS-287 XCast: retry reconnection till success

LgiHdmiCec/LgiHdmiCec.cpp, LgiHdmiCec/LgiHdmiCec.h
return value changed to 'true' for the case when
returned list is empty, but no error occured
(most likely, the case when the scanning is still
in progress). Also, when Cec is disabled, getConnectedDevices
shouldn't return failure (just empty list)
=> ARRISAPOL-2345 lgi HdmiCec getConnectedDevices retval

XCast/RtXcastConnector.cpp, XCast/RtXcastConnector.h, XCast/XCast.cpp
Previous implementation pass friendly name as a second parameter of
enable/disable xdial method. This was not implemented at xdial side and
it did not make any sense to combine these two values.
=> ONEMPERS-362 send friendlyname using dedicated handler

LgiHdmiCec/LgiHdmiCec.cpp
There's some discrepancy - cec devices list is being cleared in case when cec is disabled elsewhere (the plugin gets IARM_BUS_CECHost_EVENT_CECSTATUSCHANGE in this case; see LgiHdmiCec::onCecStatusChange). We should do the same in case cec is disabled by plugin in CECDisable.
Also, adding locks over CECEnable/CECDisable - as it is now, they can be executed concurrently which gives inconsistent results.
Additionally, do not start scanning when cec is disabled on startup (this leads to errors, since LibCCEC is not even initialized yet)
=> ARRISAPOL-2505 clean devices list on disable

OpenCDMi/CMakeLists.txt, OpenCDMi/OCDM.config
This commit partially reverts changes done in ONEM-24420
and the following pull request
https://github.com/LibertyGlobal/rdkservices/pull/109/
On top of that it implements the split according to the new approach
described here
https://wikiprojects.upc.biz/display/CTOM/Splitting+code+of+Thunder+micro+services
DEPS=meta-lgi-om-common:94525/2
=> ONEM-25360 Revert loading libraries from services directory in WPEProcess

DisplaySettings/DisplaySettings.cpp
With update to rdk displaysettings, 
USE_LGI_DEVICESETTINGS_IMPLEMENTATION blocks are not needed anymore
=> ONEMPERS-409 reenable disabled DisplaySettings code

DisplaySettings/DisplaySettings.cpp, DisplaySettings/DisplaySettings.h, HdcpProfile/HdcpProfile.cpp, HdcpProfile/HdcpProfile.h, LgiHdmiCec/LgiHdmiCec.cpp, LgiHdmiCec/LgiHdmiCec.h, XCast/XCast.cpp, XCast/XCast.h, helpers/AbstractPluginWithApiAndIARMLock.h, helpers/AbstractPluginWithApiLock.h
Review of threading safety (ONEMPERS-397) shows that
there are multiple places where rdk plugins state can
be concurrently accessed by parallel threads, without
any locking. This PR adds 'apiLock' mutex per plugin,
that assures synchronisation (and serialization) of
API method calls & IARM event handlers, to avoid
concurrency issues.
Updated plugins are:
LgiDisplaySettings/DisplaySettings
LgiHdmiCec
LgiHdcpProfile/HdcpProfile
XCast
=> ONEMPERS-411 synchronise API calls & IARM handlers

LgiHdmiCec/LgiHdmiCec.cpp, LgiHdmiCec/LgiHdmiCec.h
Seems that we can sometimes get notified about some other hdmi cec
scans that have finished, and in such case we were invalidating
scan id of the scan we are waiting for
=> ARRISAPOL-2697 do not clean scan id on another scan event

DisplaySettings/DisplaySettings.h
Without default null value, the plugin dumps on
ASSERT(m_service == nullptr);
in DisplaySettings::Initialize
=> OMWAPPI-824 fix DisplaySettings core dump

WebKitBrowser/CMakeLists.txt
After backporting full steady_clock support to condition_variable fails to build
webkitbrowser-plugin without pthread. Error message:
/usr/include/c++/9.3.0/condition_variable:201: error: undefined reference to
'pthread_cond_clockwait'
=> [ARRISEOS-43099] Fix: NTP sync up breaks timer

DisplaySettings/DisplaySettings.cpp, DisplaySettings/DisplaySettings.h, HdcpProfile/HdcpProfile.cpp, HdcpProfile/HdcpProfile.generated.json, HdcpProfile/HdcpProfile.h, HdmiCec/HdmiCec.cpp, HdmiCec/HdmiCec.h, XCast/XCast.cpp, XCast/XCast.h, helpers/AbstractPluginWithApiAndIARMLock.h, helpers/AbstractPluginWithApiLock.h
Review of threading safety (ONEMPERS-397) shows that there are multiple places where rdk plugins state can
be concurrently accessed by parallel threads, without any locking. This PR adds 'apiLock' mutex that assures synchronisation (and serialization) of API method calls & IARM event handlers, to avoid concurrency issues.
Updated plugins are:
DisplaySettings
HdmiCec
HdcpProfile
XCast
=> porting onempers-411 changes

DisplayInfo/DeviceSettings/PlatformImplementation.cpp, DisplaySettings/DisplaySettings.cpp, HdcpProfile/HdcpProfile.cpp, HdmiCec/HdmiCec.cpp, PlayerInfo/DeviceSettings/PlatformImplementation.cpp, XCast/XCast.cpp, helpers/AbstractPluginWithApiAndIARMLock.h, helpers/AbstractPluginWithApiLock.h
It is complementary function for IARM_Bus_RegisterEventHandler.
While using IARM_Bus_UnRegisterEventHandler the following could happen:
(1) Assume usage of HdmiCec and HdcpProfile plugins, both in in-process mode
(2) Activate both plugins - they both register for IARM_BUS_DSMGR_EVENT_HDMI_HOTPLUG
(3) Deactivate one of the plugin (for example HdcpProfile): IARM_Bus_UnRegisterEventHandler would de-register both listeners registrered in point (2)
(4) As a result HdcpProfile plugin will not receive IARM_BUS_DSMGR_EVENT_HDMI_HOTPLUG events anymore.
Change introduced for 6 used plugins: HdmiCec, HdcpProfile, XCast, DisplayInfo, DisplaySettings and PlayerInfo
Additionally DisplaySettings now de-register for all the events - some of them are not there previously
IARM_Bus_RemoveEventHandler API …
=> OMWAPPI-921: use IARM_Bus_RemoveEventHandler instead of IARM_Bus_UnRegisterEventHandler

XCast/CMakeLists.txt, XCast/XCast.config
Revert "ONEMPERS-198: pass XCast autostart from cmake"
replaced now by the patch that we try to upstream (standard way to do that like in the other plugins)
Revert "ONEMPERS-198: fix linking issues with XCast"
proper location of FindRFC.cmake like a Comcast use it is in wpeframework/cmake/modules/FindRFC.cmake
=> OMWAPPI-1052 remove some of our Xcast patches

DisplayInfo/DisplayInfo.cpp, PlayerInfo/PlayerInfo.cpp
This reverts commit fbf98e6bcfac6d1953359d1787cde1a3c5c6a715.
Justification:
https://jira.lgi.io/browse/OMWAPPI-1052?focusedCommentId=4702147&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4702147
Verification build done here: https://gerrit.onemw.net/c/meta-lgi-om-common/+/103659
=> Revert "ONEM-21608 - autostart configuration added for playerinfo"

XCast/XCast.cpp
no need to use XCast API to enable:
- setStandbyBehavior => default value could be set to true by -DXCAST_ENABLED_BY_DEFAULT
- setEnabled => default value could be set to true by -DXCAST_ENABLED_BY_DEFAULT_IN_STANDBY
=> ONEMPERS-685: XCast plugin enabled by default

LgiTextToSpeech/TextToSpeechImplementation.cpp
TTS::TTSManager was calling 'Dispatch' on not fully constructed TextToSpeechImplementation object, leading to virtual function call & core dump
=> ARRISAPP-65 fix the race on TextToSpeechImplementation constr

LgiNetwork/Network.cpp, LgiNetwork/Network.h, LgiNetwork/dbus/lginetwork_client.cpp, LgiNetwork/dbus/lginetwork_client.hpp
- update logic to correctly report onIPAddressStatusChanged for both IP v4 and v6
- also send LOST when DISCONNECTED
- handle IPvXConfigurationChanged events and refresh the IPs when received; necessary to have onIPAddressStatusChanged for IPv6 when rebooting the router/WiFi is lost and reacquired (we get no configuration.changed/network.changed event in such case, and dhcp6.options never actually seems to report ip v6 at all)
=> ARRISAPP-85 onIPAddressStatusChanged for ipv6

HdmiCec/HdmiCec.cpp, HdmiCec/HdmiCec.h
* use: IARM_BUS_CECHost_EVENT_ACTIVESTATUSCHANGE (event) and IARM_BUS_CEC_HOST_GetActiveStatus method
* removed all the methods/members that starts/control scanning
controlled via: LGI_CUSTOM_IMPL flag
verification: https://gerrit.onemw.net/c/meta-lgi-om-common/+/103853
=> ARRISAPP-59: LGI specific implementation

HdmiCec/HdmiCec.cpp
Done in the following way:
=> do not register for not required IARM events:
* IARM_BUS_CECMGR_EVENT_DAEMON_INITIALIZED/IARM_BUS_CECMGR_EVENT_STATUS_UPDATED: cecMgrEventHandler=> onCECDaemonInit and cecStatusUpdated never called
* IARM_BUS_DSMGR_EVENT_HDMI_HOTPLUG: dsHdmiEventHandler=> onHdmiHotPlug never called
=> HdmiCec::CECDisable and HdmiCec::CECEnable: implementation just toggle the flag (rest is removed)
=> HdmiCec::sendMessage: stub implementation
As a result plugin functionality limited only to the following functional subset:
* org.rdk.HdmiCec.1.getActiveSourceStatus
* onActiveSourceStatusUpdated event
all the other methods/events:
* org.rdk.HdmiCec.1.setEnabled/org.rdk.HdmiCec.1.getEnabled - just toggle the flag
* scanning of HDMI CEC devices not performed: …
=> ARRISAPP-186: cut-off not used HdmiCec plugin functionality

OpenCDMi/LibertyConfig.cpp, OpenCDMi/LibertyConfig.h
Since we're using lgias config, we should wait for application services 'ready' event before we expect to get some lgias data.
=> OMWAPPI-1614 wait for lgias 'ready' in OpenCDMi

OpenCDMi/FrameworkRPC.cpp
Since WideVine configuration needs lgias data and in some scenarios (Factory Reset!) this data is not readily available at boot time, we defer the initialization of Widevine until CreateSession.
=> OMWAPPI-1614 ocdm: lazy init for WideVine

WebKitBrowser/WebKitImplementation.cpp
In this task we disable clipping for all aps not only STV, so we don't need stv link check.
Revert "[HUMAXEOS-4885]: Disable Gstreamer clipping for STV app"
=> [ONEM-30000]: Disable clipping mechanism in gst for all apps

WebKitBrowser/CMakeLists.txt, WebKitBrowser/WebKitImplementation.cpp
The browser should send ODH report when the metro app quits after pressing back key. This path was not covered as after pressing back key, the metro app itself loads boot url.
This commit also adds integration from legacy browser for reading properties from Dbus as we needed this to get device boot url.
=> [ARRISEOS-43922]: Send bootURL ODH report after quitting metro app

DisplaySettings/DisplaySettings.cpp, DisplaySettings/DisplaySettings.h
Upstream patch 0001-displaysettings-lgi-extensions.patch to LGI fork.
Added API added to:
a) set resolution change onwer (to block resolution change by other modules during a follow framerate trasnition) 
b) get port video enabled status
c) enable/disable video port
author: Roman Slipko (rslipko@libertyglobal.com)
validation: https://gerrit.onemw.net/c/meta-lgi-om-common/+/107945/1/
=> ARRISAPP-285: upstream patch to fork

WebKitBrowser/WebKitImplementation.cpp
"enable-websecurity" property no longer exists, it has been replaced by "disable-web-security"
"disable-web-security" is not related to mixed content though, it disables the same-origin policy, so it's best not to touch it in this case
=> ONEM-30654: Fix enabling mixed content

PlayerInfo/DeviceSettings/PlatformImplementation.cpp, PlayerInfo/PlayerInfo.json
While kSurroundMatFollow has been added ([OMWAPPI-1653](https://jira.lgi.io/browse/OMWAPPI-1653)),
the support is still missing in thunder PlayerInfo plugin.
The change depends on update in wpeframework interfaces (device::AudioStereoMode::kSurroundMatFollow must also be added there)
=> ARRISAPP-394 add STEREO_SURROUND_MAT_FOLLOW

OpenCDMi/FrameworkRPC.cpp
This change is just temporary to collect data on how often OCDM secure store gets modified or deleted.
=> ONEM-30768 Add ODH report for OCDM secure store operations

OCIContainer/CMakeLists.txt, OCIContainer/OCIContainer.cpp, OCIContainer/OCIContainer.h, OCIContainer/OCIContainer.json, OCIContainer/doc/OCIContainerPlugin.md, OCIContainer/stubs/i_omi_proxy.hpp, OCIContainer/stubs/omi_proxy.hpp
Changelog:
- Prepares OMI to be upstreamed
- Fixes OMI mount leakage in case of Dobby start failure.
Note: it's the same as https://github.com/LibertyGlobal/rdkservices/pull/258
no_jenkins
In order to apply cleanly this patch the following were also cherry-picked:
commit 35a99df1e46f9604bcd128adccbd9e35c64e2b8a
Author: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>
Date:   Wed Jul 5 14:56:37 2023 +0200
[OCIContainer] Improve error reporting.
Cherry picks missing patch from branch: lgi-main-20220329
https://github.com/LibertyGlobal/rdkservices/commit/7ce738ef7a8cd71665f68a768b2163fbe224daea
commit 206e08d124a83927cefde8ff587267321873bc62
Author: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>
Date:   Wed Jul 5 14:48:31 2023 +0200
ONEM-19817: Extend OCIContainer Thunder Plugin to support crypted …
=> ONEM-30706 OMI upstreaming

WebKitBrowser/Extension/CMakeLists.txt, WebKitBrowser/Extension/CORSWhiteListedOriginDomainsList.cpp, WebKitBrowser/Extension/CORSWhiteListedOriginDomainsList.h, WebKitBrowser/Extension/MixedContentWhiteListedOriginDomainsList.cpp, WebKitBrowser/Extension/MixedContentWhiteListedOriginDomainsList.h, WebKitBrowser/Extension/WhitelistBase.h, WebKitBrowser/Extension/main.cpp, WebKitBrowser/WebKitBrowser.config, WebKitBrowser/WebKitBrowserPlugin.json, WebKitBrowser/WebKitImplementation.cpp
Controlled via mixedcontentwhitelist entry in plugin config, '*' can be used as a wildcard. Passed to webkit via libextension, similiar to how CORS whitelist works.
Removed the CORS whitelist as we don't need it
=> ONEM-31369: Implement whitelist for mixed content

WifiManager/impl_lg/dbus/DBusClient.cpp
Deallocating return values from g_variant_iter_next_value was missing, and this causes leaking GVariants: https://developer-old.gnome.org/glib/stable/glib-GVariant.html#g-variant-iter-next-value
=> ARRISAPP-438 fix WifiManager leaks
