LibertyGlobal/rdkservices

FireboltMediaPlayer/FireboltMediaPlayer.cpp
It causes problems (crashes) in another scenario:
(1) Activate FMP
(2) Start playback
(3) Deactivate FMP through controller
=> ONEM-20048: removed unregister

PlayerInfo/DeviceSettings/PlatformImplementation.cpp
Out of process plugin requires initialization of connetion to IARM daemon.
=> HUMAXEOSR-798: playerinfo: iarm initialization added

PlayerInfo/PlayerInfo.cpp, PlayerInfo/PlayerInfo.h
Support for running PlayerInfo as out-of-process plugin was added:
- audioCodecs/VideoCodecs unregistrationg added
- connection deactivated listener added
- proper support in case of out-of-thunder plugin termination
=> HUMAXEOSR-828: PlayerInfo: support for out-of-process

DisplayInfo/DisplayInfo.cpp, PlayerInfo/PlayerInfo.config, PlayerInfo/PlayerInfo.cpp
DEPS=meta-lgi-om-common:83688/6
=> ONEM-21608 - autostart configuration added for playerinfo

OCIContainer/CMakeLists.txt, OCIContainer/OCIContainer.cpp, OCIContainer/OCIContainer.h, OCIContainer/OCIContainer.json, OCIContainer/stubs/i_omi_proxy.hpp, OCIContainer/stubs/omi_proxy.hpp
=> ONEM-19817: Extend OCIContainer Thunder Plugin to support crypted

DisplaySettings/DisplaySettings.cpp
https://github.com/rdkcentral/rdkservices/commit/69aac637d06f5c24a4dcdd12612b2e5c076e33e1
Author: Anooj Cheriyan <Anooj_Cheriyan@comcast.com>
Date:   Mon Sep 20 15:41:14 2021 +0000
RDKCOM-2394: org rdk DisplaySettings deactivate fails
Reason for change:
org rdk DisplaySettings deactivate fails
Test Procedure: None
Risks: Low
Change-Id: I7002de7a70f5d00115cb29743a19c516dc10e8a7
Signed-off-by: Anooj Cheriyan <Anooj_Cheriyan@comcast.com>
(cherry picked from commit 4c947140f1495f63199e35d075ed437a68bff63a)
=> [HUMAXEOSR-951] backporting 69aac637d06f5c24a4dcdd12612b2e5c076e33e1

LgiDisplaySettings/LgiDisplaySettings.json, LgiDisplaySettings/doc/LgiDisplaySettingsPlugin.md
Updated documentation - new plugin methods added
=> HUMAXEOSR-963 update LgiDisplaySettings docs

WebKitBrowser/WebKitImplementation.cpp
When #boot url is set force reloading it.
=> [ARRISEOS-40798] WebKitBrowser: Fix #boot url reload

OpenCDMi/OCDM.config
Signed-off-by: Gurdal Oruklu <gurdal_oruklu@comcast.com>
(cherry picked from commit 9b1f5bf09a24f9e3cfb316a9b4c05e36a8ddbe57)
=> COMCAST: set OCDM sharepath to /tmp/OCDM

WebKitBrowser/WebKitImplementation.cpp
+ replace WKContextSetGnuTlsCipherPriority with WKContextSetEnv
no_jenkins
=> ONEM-22561: activate delay key events for BBCSounds

WebKitBrowser/WebKitImplementation.cpp
=> ONEM-24154 Wait for SetURL result (with timeout). Moved workarounds code into

LgiHdmiCec/LgiHdmiCec.cpp, LgiHdmiCec/LgiHdmiCec.h
onDevicesChanged event should be signaled when HDMI CEC gets enabled/disabled.
=> Signal onDevicesChanged on HDMI CEC device list update

LgiDisplaySettings/LgiDisplaySettings.json
get/setZoomSetting should be accepting string, not bool
=> ONEMPERS-316 small fix in display settings json

WebKitBrowser/WebKitImplementation.cpp
IStringIterator arguments were causing crash of wpeframework.
Use 'clear' word to signalize remove of jss / css injections.
=> [ARRISEOS-41993] Use string arguments in IBrowser interface]

WebKitBrowser/WebKitImplementation.cpp
IStringIterator arguments were causing crash of wpeframework.
Use 'clear' word to signalize remove of jss / css injections.
=> [ARRISEOS-41993] Use string arguments in IBrowser interface

XCast/CMakeLists.txt, XCast/XCast.cpp, helpers/powerstate.cpp, helpers/powerstate.h
onXcastSystemApplicationSleepRequest lets box enter
standby mode via dial invocation
=> ONEMPERS-398 onXcastSystemApplicationSleepRequest implementation

WebKitBrowser/WebKitImplementation.cpp
=> ONEM-27605: Set WPE_INIT_VIEW_HEIGHT / WIDTH envs

WebKitBrowser/CMakeLists.txt
=> [ARRISEOS-43099] Fix: NTP sync up breaks timer

DisplaySettings/CMakeLists.txt, DisplaySettings/DisplaySettings.config, HdcpProfile/CMakeLists.txt, HdcpProfile/HdcpProfile.config, HdmiCec/CMakeLists.txt, HdmiCec/HdmiCec.config
Verification build: https://jenkins.onemw.net/job/EngineeringBuild/16888/parameters/ (that branch + plugins configured autostart)
=> Onem 29035 unified autostart setup

HdmiCec/HdmiCec.cpp, HdmiCec/HdmiCec.h
This reverts commit 45191c25a3b59d1e1ac161c63c87f83512c240bc.
=> Revert "ARRISAPP-59: setup activeSource from HdmiCec plugin"

HdmiCec/HdmiCec.cpp, HdmiCec/HdmiCec.h, HdmiCec/HdmiCec.json
Verification build: https://jenkins.onemw.net/job/CI/job/verify-vip7002w-rdk14_oe31/1277/OM_BRANCH=rdk14_oe31,OM_BUILD_TYPE=dbg,label=onemw-build-u20-04/
=> ONEM-29592: [dev] implementation of com.lgi.rdk.HdmiCec.1.triggerAction

WifiManager/CMakeLists.txt, WifiManager/WifiManager.cpp, WifiManager/WifiManager.h, WifiManager/impl/WifiImplementation.h, WifiManager/impl_lg/WifiImplementation.h, WifiManager/impl_lg/WifiManagerConnect.cpp, WifiManager/impl_lg/WifiManagerConnect.h, WifiManager/impl_lg/WifiManagerEvents.cpp, WifiManager/impl_lg/WifiManagerEvents.h, WifiManager/impl_lg/WifiManagerScan.cpp, WifiManager/impl_lg/WifiManagerScan.h, WifiManager/impl_lg/WifiManagerSignalThreshold.cpp, WifiManager/impl_lg/WifiManagerSignalThreshold.h, WifiManager/impl_lg/WifiManagerState.cpp, WifiManager/impl_lg/WifiManagerState.h, WifiManager/impl_lg/WifiManagerWPS.cpp, WifiManager/impl_lg/WifiManagerWPS.h, WifiManager/impl_lg/dbus/DBusClient.cpp, WifiManager/impl_lg/dbus/DBusClient.h, WifiManager/impl_lg/dbus/networkconfig1_dbus_api.c, WifiManager/impl_lg/dbus/networkconfig1_dbus_api.h, WifiManager/impl_lg/dbus/wifimanagement1_dbus_api.c, WifiManager/impl_lg/dbus/wifimanagement1_dbus_api.h, WifiManager/impl_lg/dbusgen/gencode.sh
Lgi specific implementation based on dbus ifaces:
com.lgi.rdk.utils.networkconfig1
com.lgi.rdk.utils.wifimanagement1
Only following methods and events are supported
for now:
methods:
setSignalThresholdChangeEnabled
getCurrentState
getConnectedSSID
events:
onWIFIStateChanged
onWifiSignalThresholdChanged
onSSIDsChanged
(this should be enough for Amazon app)
=> OMWAPPI-1620: org.rdk.Wifi implementation

WifiManager/impl_lg/WifiManagerSignalThreshold.cpp, WifiManager/impl_lg/WifiManagerState.cpp, WifiManager/impl_lg/WifiManagerState.h
Verification build: https://jenkins.onemw.net/job/EngineeringBuild/19896/
=> ARRISAPP-290: WifiManager: returning bssid, security, strength, band

WebKitBrowser/CMakeLists.txt, WebKitBrowser/Extension/AAMPJSBindings.cpp, WebKitBrowser/WebKitBrowser.cpp, WebKitBrowser/WebKitBrowser.h, WebKitBrowser/WebKitBrowserJsonRpc.cpp, WebKitBrowser/WebKitImplementation.cpp
Current goal is to run WPE 2.38. All R4 plugin dependencies which are not compiling on this initial stage of integration are not important.
=> [ONEM-30099] Comment all not compiling Webkit interfaces

XCast/XCast.cpp
to pass NTS test case SUSP-006-TC3
=> ARRISAPP-295: try to decrease-retry-timeout

XCast/XCast.cpp
to pass NTS test case SUSP-006-TC3
verification build: https://jenkins.onemw.net/job/EngineeringBuild/20113/ (VIP7002W-mon-dbg-06.02-166-ae-[AL-20230427152620](https://jira.lgi.io/browse/AL-20230427152620)-un000)
=> ARRISAPP-295: decrease retry timeout

WebKitBrowser/CMakeLists.txt
This reverts commit ca96f8d971229fc000e19d325c6e81ba15f9b5b9.
=> Revert "[ONEM-30099] Remove Extension dependency"

WebKitBrowser/WebKitBrowser.cpp, WebKitBrowser/WebKitBrowser.h, WebKitBrowser/WebKitImplementation.cpp
It allows to set user script and user stylesheet
=> [ONEM-30104] Implement BrowserResources interface in WebKitBrowser plugin

LgiNetwork/Network.cpp, LgiNetwork/Network.h, LgiNetwork/Network.json
Also some changes to properly raise other
events:
- onInterfaceStatusChanged
- onInterfaceStatusChanged
onIPAddressStatusChanged already tested & should work ok.
=> ONEM-30984 onDefaultInterfaceChanged in LgiNetwork

LgiNetwork/Network.cpp, LgiNetwork/Network.h, LgiNetwork/Network.json, OpenCDMi/FrameworkRPC.cpp
backporting 2 changes:
- ONEM-30768 - 'Add ODH report for OCDM secure store operations'
- ONEM-30984 - 'onDefaultInterfaceChanged in LgiNetwork'
=> backporting changes from lgi-changes-from-lgi-main-20220329

LgiNetwork/Network.cpp, LgiNetwork/Network.json
add 'prefix_length' property in responses to
org.rdk.Network.1.getIPSettings invocations in
LgiNetwork plugin
=> ONEM-31168 org.rdk.Network.1.getIPSettings prefix

WebKitBrowser/WebKitBrowser.config
=> ONEM-31159: Add whitelits for https://broadcast.live.bbctvapps.co.uk/

WebKitBrowser/WebKitImplementation.cpp
Verification change: https://gerrit.onemw.net/c/meta-lgi-wpe/+/109607
Verification builds:
https://jenkins.onemw.net/job/EngineeringBuild/22302/ (Th4.1 + WPE2.38) 
https://jenkins.onemw.net/job/EngineeringBuild/22303/ (Th2.1.12 + WPE2.38)
=> OMWAPPI-1995: Webkitbrowser plugin compilation error

OCIContainer/CMakeLists.txt, OCIContainer/OCIContainer.cpp
Preparing changes to be upstreamed
no_jenkins
=> ONEM-30706 OMI upstreaming

WebKitBrowser/BrowserConsoleLog.h, WebKitBrowser/Extension/main.cpp, WebKitBrowser/InjectedBundle/main.cpp, WebKitBrowser/WebKitImplementation.cpp
changes comes from the following commit:
=> https://github.com/WebPlatformForEmbedded/ThunderNanoServicesRDK/commit/3f6b35550d564700bf59f8f64cd2ab1d98b2a637 => https://github.com/WebPlatformForEmbedded/ThunderNanoServicesRDK/commit/6481174ec89d80b033edfa29b04528fe4d09285f
=> ONEM-30922: compile LGI browser plugin on R4.3

WebKitBrowser/WebKitImplementation.cpp
The API is still there, but calling it won't have any effect.
Mixed content mode will depend on the value of
WEBKITBROWSER_SECURE property in the recipe, and it'll be disabled
(not allowed outside of what is whitelisted) by default
=> ONEM-31702: Disable the API for switching mixed content mode

WebKitBrowser/WebKitImplementation.cpp
This is a port of following commit:
https://github.com/LibertyGlobal/rdkservices/commit/17775a52e30959c386ee45bb844ad4076241b841
=> ONEM-31440: Read main configuartion via DBus

LgiNetwork/dbus/lginetwork_client.cpp
Deallocating return values from g_variant_iter_next_value was missing, and this causes leaking GVariants:
https://developer-old.gnome.org/glib/stable/glib-GVariant.html#g-variant-iter-next-value
=> ARRISAPP-438 fix more LgiNetwork leaks

LgiNetwork/dbus/lginetwork_client.cpp, WifiManager/impl_lg/dbus/DBusClient.cpp
=> ARRISAPP-438 fix LgiNetwork & WifiManager leaks

LgiNetwork/dbus/lginetwork_client.cpp, WifiManager/impl_lg/dbus/DBusClient.cpp
=> ARRISAPP-438 LgiNetwork & WifiManager leaks

TraceControl/TraceControl.h
correcting issues flagged by SonarQube
=> ARRISEOS-44764 SonarQube: TraceControl

DisplaySettings/DisplaySettings.cpp, helpers/UtilsSynchro.hpp, helpers/UtilsisValidInt.h
correcting issues found by SonarQube
=> ARRISEOS-44757 SonarQube: rdkservice-displaysettings

LgiSystemServices/SystemServicesHelper.cpp, LgiSystemServices/SystemServicesHelper.h
correcting issues flagged by SonarQube
=> ARRISEOS-44761 SonarQube: rdkservice-lgi-system

HdmiCec/HdmiCec.cpp, HdmiCec/HdmiCec.h
correcting issues flagged by SonarQube
=> ARRISEOS-44759 SonarQube: rdkservice-hdmicec

LgiNetwork/NetUtilsNetlink.cpp, LgiNetwork/dbus/lginetwork_client.cpp
=> ARRISEOS-44760 SonarQube: rdkservice-lgi-network

DisplayInfo/DeviceSettings/PlatformImplementation.cpp, DisplayInfo/DisplayInfo.h
=> ARRISEOS-44756 static code analysis in displayinfo

XCast/RtXcastConnector.h, XCast/XCast.cpp, XCast/XCastCommon.h
correcting issues found by SonarQube
=> ARRISEOS-44766 SonarQube: rdkservice-xcast

PlayerInfo/DeviceSettings/PlatformImplementation.cpp, PlayerInfo/GStreamer/PlatformImplementation.cpp, PlayerInfo/PlayerInfo.cpp, PlayerInfo/PlayerInfo.h
=> ARRISEOS-44763 SonarQube issues: playerinfo
